_include_yml: kairos

# CIC-IDS-2017 has only netflow nodes (IP addresses).
# subject and file node types do not exist in this dataset.
construction:
  node_label_features:
    subject: ""
    file: ""
    netflow: remote_ip, remote_port

evaluation:
  ground_truth_version: none
