import torch 
from torch import nn
from torch.distributed import rpc 

from .euler_interface import Euler_Encoder, Euler_Recurrent
from .utils import _remote_method, _remote_method_async

class DetectorEncoder(Euler_Encoder):
    '''
    Detector implimentation of Euler_Encoder interface
    '''

    def __init__(self, module, **kwargs):
        super().__init__(module, **kwargs)

        # KDE decode MLP: additive logit adjustment from KDE vectors
        kde_dim = getattr(self.module.data, 'kde_dim', 0)
        self._kde_dim = kde_dim
        if kde_dim > 0:
            mlp_h = max(kde_dim // 2, 8)
            self.module.kde_mlp = nn.Sequential(
                nn.Linear(kde_dim, mlp_h),
                nn.ReLU(),
                nn.Linear(mlp_h, 1)
            )
            print(f"  KDE decode MLP created: {kde_dim} -> {mlp_h} -> 1 ({sum(p.numel() for p in self.module.kde_mlp.parameters())} params)")

    def _get_kde_vecs(self, ei, i=None):
        '''Look up KDE vectors for an edge list. Returns tensor or None.'''
        if self._kde_dim == 0:
            return None
        src, dst = ei
        return self.module.data.get_kde_tensor(src, dst)

    def decode_all(self, zs, unsqueeze=False):
        '''
        Given node embeddings, return edge likelihoods for 
        all subgraphs held by this model
        For detector model, it's very simple. Just return the embeddings
        for ei[n] given zs[n]

        zs : torch.Tensor
            A T x d x N tensor of node embeddings generated by the models, 
            it is safe to assume z[n] are the embeddings for nodes in the 
            snapshot held by this model's TGraph at timestep n
        '''
        assert not zs.size(0) < self.module.data.T, \
            "%s was given fewer embeddings than it has time slices"\
            % rpc.get_worker_info().name

        assert not zs.size(0) > self.module.data.T, \
            "%s was given more embeddings than it has time slices"\
            % rpc.get_worker_info().name

        preds = []
        ys = []
        cnts = []
        for i in range(self.module.data.T):
            ei = self.module.data.eis[i]
            kde_vecs = self._get_kde_vecs(ei, i)
            preds.append(
                self.decode(ei, zs[i], kde_vecs=kde_vecs)
            )    
            ys.append(self.module.data.ys[i])
            cnts.append(self.module.data.cnt[i])

        return preds, ys, cnts

    def decode_all_with_edges(self, zs, unsqueeze=False):
        '''
        Same as decode_all but also returns edge indices per snapshot,
        enabling per-edge prediction tracking for post-processing.
        Returns (preds, ys, cnts, eis) where eis[i] is the edge index
        tensor for snapshot i.
        '''
        assert not zs.size(0) < self.module.data.T, \
            "%s was given fewer embeddings than it has time slices"\
            % rpc.get_worker_info().name

        assert not zs.size(0) > self.module.data.T, \
            "%s was given more embeddings than it has time slices"\
            % rpc.get_worker_info().name

        preds = []
        ys = []
        cnts = []
        eis = []
        for i in range(self.module.data.T):
            ei = self.module.data.eis[i]
            kde_vecs = self._get_kde_vecs(ei, i)
            preds.append(
                self.decode(ei, zs[i], kde_vecs=kde_vecs)
            )
            ys.append(self.module.data.ys[i])
            cnts.append(self.module.data.cnt[i])
            eis.append(ei)

        return preds, ys, cnts, eis

    def score_edges(self, z, partition, nratio):
        '''
        Given a set of Z embeddings, returns likelihood scores for all known
        edges, and randomly sampled negative edges

        z : torch.Tensor
            A T x d x N tensor of node embeddings generated by the models, 
            it is safe to assume z[n] are the embeddings for nodes in the 
            snapshot held by this model's TGraph at timestep n
        partition : int 
            An enum representing if this is training/validation/testing for 
            generating negative edges 
        nratio : float
            The model samples nratio * |E| negative edges for calculating loss
        '''
        n = self.module.data.get_negative_edges(partition, nratio)

        p_scores = []
        n_scores = []

        for i in range(len(z)):
            p = self.module.data.ei_masked(partition, i)
            if p.size(1) == 0:
                continue

            kde_vecs_p = self._get_kde_vecs(p, i)
            p_scores.append(self.decode(p, z[i], kde_vecs=kde_vecs_p))
            # Negative edges: no KDE vectors (pass None)
            n_scores.append(self.decode(n[i], z[i]))

        p_scores = torch.cat(p_scores, dim=0)
        n_scores = torch.cat(n_scores, dim=0)

        return p_scores, n_scores

    def calc_loss(self, z, partition, nratio):
        '''
        Sum up all of the loss per time step, then average it. For some reason
        this works better than running score edges on everything at once. It's better
        to run BCE per time step rather than all at once

        z : torch.Tensor
            A T x d x N tensor of node embeddings generated by the models, 
            it is safe to assume z[n] are the embeddings for nodes in the 
            snapshot held by this model's TGraph at timestep n
        partition : int 
            An enum representing if this is training/validation/testing for 
            generating negative edges 
        nratio : float
            The model samples nratio * |E| negative edges for calculating loss
        '''
        tot_loss = torch.zeros(1)
        ns = self.module.data.get_negative_edges(partition, nratio)

        for i in range(len(z)):
            ps = self.module.data.ei_masked(partition, i)
            
            # Edge case. Prevents nan errors when not enough edges
            # only happens with very small timewindows 
            if ps.size(1) == 0:
                continue

            kde_vecs_p = self._get_kde_vecs(ps, i)
            tot_loss += self.bce(
                self.decode(ps, z[i], kde_vecs=kde_vecs_p),
                self.decode(ns[i], z[i])  # negatives: no KDE
            )

        return tot_loss.true_divide(len(z))


class DetectorRecurrent(Euler_Recurrent):
    def score_all(self, zs, unsqueeze=False):
        '''
        Has the distributed models score and label all of their edges
        Sends workers embeddings such that zs[n] is used to reconstruct graph at 
        snapshot n

        zs : torch.Tensor 
            A T x d x N tensor of node embeddings generated by each graph snapshot
            Need to offset according to how far in the future embeddings are supposed
            to represent.
        '''
        futs = []
        start = 0
    
        for i in range(self.num_workers):
            end = start + self.len_from_each[i]
            futs.append(
                _remote_method_async(
                    DetectorEncoder.decode_all,
                    self.gcns[i],
                    zs[start : end],
                    unsqueeze=unsqueeze
                )
            )
            start = end 

        obj = [f.wait() for f in futs]
        scores, ys, cnts = zip(*obj)
        
        # Compress into single list of snapshots
        scores = sum(scores, [])
        ys = sum(ys, [])
        cnts = sum(cnts, [])

        return scores, ys, cnts


    def score_all_with_edges(self, zs, unsqueeze=False):
        '''
        Same as score_all but also returns edge indices per snapshot.
        Returns (scores, ys, cnts, eis).
        '''
        futs = []
        start = 0

        for i in range(self.num_workers):
            end = start + self.len_from_each[i]
            futs.append(
                _remote_method_async(
                    DetectorEncoder.decode_all_with_edges,
                    self.gcns[i],
                    zs[start : end],
                    unsqueeze=unsqueeze
                )
            )
            start = end

        obj = [f.wait() for f in futs]
        scores, ys, cnts, eis = zip(*obj)

        scores = sum(scores, [])
        ys = sum(ys, [])
        cnts = sum(cnts, [])
        eis = sum(eis, [])

        return scores, ys, cnts, eis


    def loss_fn(self, zs, partition, nratio=1):
        '''
        Runs NLL on each worker machine given the generated embeds
        Sends workers embeddings such that zs[n] is used to reconstruct graph at 
        snapshot n

        zs : torch.Tensor 
            A T x d x N tensor of node embeddings generated by each graph snapshot
            Need to offset according to how far in the future embeddings are supposed
            to represent.
        partition : int
            enum representing train, validation, test sent to workers
        nratio : float
            The workers sample nratio * |E| negative edges for calculating loss
        '''
        futs = []
        start = 0
    
        for i in range(self.num_workers):
            end = start + self.len_from_each[i]
            futs.append(
                _remote_method_async(
                    DetectorEncoder.calc_loss,
                    self.gcns[i],
                    zs[start : end],
                    partition, nratio
                )
            )
            start = end 

        tot_loss = torch.zeros(1)
        for f in futs:
            tot_loss += f.wait()

        return [tot_loss.true_divide(self.num_workers)]
        

    def score_edges(self, zs, partition, nratio=1):
        '''
        Gets edge scores from dist modules, and negative edges. 
        Sends workers embeddings such that zs[n] is used to reconstruct graph at 
        snapshot n

        zs : torch.Tensor 
            A T x d x N tensor of node embeddings generated by each graph snapshot
            Need to offset according to how far in the future embeddings are supposed
            to represent.
        partition : int
            enum representing train, validation, test sent to workers
        nratio : float
            The workers sample nratio * |E| negative edges for calculating loss
        '''
        futs = []
        start = 0
    
        for i in range(self.num_workers):
            end = start + self.len_from_each[i]
            futs.append(
                _remote_method_async(
                    DetectorEncoder.score_edges,
                    self.gcns[i],
                    zs[start : end], 
                    partition, nratio
                )
            )
            start = end 

        pos, neg = zip(*[f.wait() for f in futs])
        return torch.cat(pos, dim=0), torch.cat(neg, dim=0)